Задача 1. Реализация обхода в ширину (BFS – LEVELS)
IlyaMuravjov/high-performance-graph-analysis-course pull request #1
Opened 2023-03-12 11:04 UTC by IlyaMuravjov

# Задача 1. Реализация обхода в ширину (BFS – LEVELS)

* **Мягкий дедлайн**: 12.03.2023, 23:59
* **Жёсткий дедлайн**: 15.03.2023, 23:59
* Полный балл: 5

## Подготовка
- [x] Сделать публичный `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1VAfnSGd63GulSdig8TLISOXBF7MMIUm3egO4U_jdugI/edit?usp=sharing).
- [x] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/1VAfnSGd63GulSdig8TLISOXBF7MMIUm3egO4U_jdugI/edit?usp=sharing))

## Задача

Везде считаем, что вершины графа занумерованы подряд с нуля.

- [x] Используя pygraphblas реализовать функцию обхода ориентированного графа в ширину из заданной вершины. При этом организовать все вычисления в виде операций над векторами и матрицами.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [x] Функция возвращает массив, где для каждой вершины указано, на каком шаге она достижима. Стартовая вершина достижима на нулевом шаге, если вершина не достижима, то значение соответствующей ячейки равно -1.
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
    - Проверить, что тесты запускаются только на linux.

2023-03-14 10:03 UTC, rustam-azimov requested changes

2023-03-14 10:03 UTC, rustam-azimov commented on project/bfs.py
> +    while True:
лучше пока Фронт не пуст

2023-03-14 10:03 UTC, rustam-azimov commented on project/bfs.py
> +    res = pgb.Vector.dense(pgb.INT64, num_vertices, fill=-1)
если -1 после цикла заполнить, то можно обойтись без visited. Вместо него в масках использовать res.

2023-03-14 16:40 UTC, IlyaMuravjov commented on project/bfs.py
> +    while True:
Изменил

2023-03-14 16:40 UTC, IlyaMuravjov commented on project/bfs.py
> +    res = pgb.Vector.dense(pgb.INT64, num_vertices, fill=-1)
Изменил

2023-03-18 06:49 UTC, rustam-azimov approved these changes
5 баллов

2023-03-18 08:29 UTC, merged